### ISSUE TITLE
[Meta ticket] Roadmap for migrating diagnostics to ROS 2

### ISSUE THREAD

**Issue by ralph-lange** [boschresearch/ros2_diagnostics#1]
Meta Ticket tracking the progress of migrating diagnostics to ros2:

We propose the following next PRs:

- [x]  Add ament_ignore to all non-migrated packages. See https://github.com/ros/diagnostics/pull/101
- [x]  Port diagnostic_updater package. See https://github.com/ros/diagnostics/pull/102
- [x]  Port self_test package. See https://github.com/ros/diagnostics/pull/104
- [ ]  Port diagnostic_common_diagnostics package
- [x]  Port diagnostic_aggregator package
   - [ ]  Also port bond_core, bondcpp
- [ ] Port test_diagnostic_aggregator
- [ ]  rosdiagnostic (or integrate this tool with https://github.com/ros2/ros2cli)

We do not plan to port diagnostic_analysis.

Questions:
- Is this order fine for you, @trainman419 ?
- Any thoughts on the order of the other packages?

**Comment by trainman419** [comment]
That sounds great. I don't really have an opinion on the porting order.

**Comment by norro** [comment]
@Karsten1987 I would offer to help with the migration. However, as I am probably much slower than you are, I should probably focus on an isolated package to avoid slowing you down. Both, `diagnostic_common_diagnostics` as well as `diagnostic_aggregator`, seem to be feasible. Do you have a preference, which package I should attempt migrating?

**Comment by ralph-lange** [comment]
Regarding the migration of bond: We should first analyze the liveliness mechanisms provided by DDS (cf. Section 2.2.3.11 of the DDS standard v1.4, which is available at https://www.omg.org/cgi-bin/doc?formal/15-04-10.pdf).

**Comment by Karsten1987** [comment]
@ralph-lange where I actually agree with the liveliness I am somewhat unhappy with relying on DDS only features in high level packages. Generally, I still feel that ROS2 should stay DDS agnostic and therefore possibly support different middleware types.
That being said, the discussion about it is happening here: https://github.com/ros2/design/pull/212

@norro Given Ralph's comment, I would support the idea that you guys have a look at the liveliness or DDS features which could be used and make a judgement call on the `diagnostics_aggregator`. I'll then start with the `diagnostic_common_diagnostics` package. I am of course always happy to help in case you've got questions.

**Comment by norro** [comment]
I recently started migration of the `diagnostic_aggregator` package. It is still raw and not able to compile, mainly due to: migration of parameter handling, migration of logging (originally had lots of logging outside nodes), and testing.
I didn't push so far as it is still in a raw shape.

**Comment by norro** [comment]
Migration of C++ API done, see https://github.com/ros/diagnostics/compare/ros2-devel...boschresearch:ros2_migrate_diagnostic_aggregator. 
@Karsten1987 Compiles without errors and warnings. Note: If you want to build it (e.g., CI) remember that it currently needs the bond_core from PR#43, i.e. https://github.com/kishornaik10/bond_core/tree/ros2-devel

**Comment by norro** [comment]
Migration of larger python parts is blocked as bondpy is not yet ported to ros2, see discussion in https://github.com/ros/bond_core/pull/43
